### ISSUE TITLE
Bob learn doesn't exist

### ISSUE THREAD

**Issue by mavrokefalidis** [jindongwang/transferlearning#166]
bob.learn is not a package and it's part of the file GFK.py which leads to not being able to run this file since due to unresolved dependencies:

ModuleNotFoundError: No module named 'bob.learn'

**Comment by jindongwang** [comment]
Unfortunately yes. We may not be able to use bob any more. Therefore, the code of GFK in python is also not available since to achieve the same results in Matlab, we need to use bob library.
Therefore, I can do nothing about it except suggesting that you use the Matlab version instead. If you still want to use Python code, then you can try to call the Matlab code in your Python script by following some tutorials online.

**Comment by mavrokefalidis** [comment]
Would it be possible to use the sklearn implementation of PCA?

**Comment by jindongwang** [comment]
I tried PCA, but the results are not the same.
