### ISSUE TITLE
Whether to normalize the test data  **with train data**？

### ISSUE THREAD

**Issue by wac81** [jindongwang/transferlearning#262]
in your adarnn project you mentioned:
`This process is accomplished by max-min normalization and ranges data between 0 and 1`

Whether to normalize the test data  **with train data**

your paper mentioned stock prediction, can you provide the code? I want to know the input & output. Is the output the predicted stock price for the next day?

**Comment by jindongwang** [comment]
@wac81 Thanks for your interest in this work. Regarding your questions:

1. The normalization of train-val-test remains an engineering problem that does not have a definite solution. Actually, someone prefers to normalize first, then split train-test-val; someone prefers to split, then normalize each set with its own statistics. In our work, we adopt the latter: split train-val-test, then normalize each set with only the train statistics. The reason is that test set is actually unseen during training, and the training process cannot have any information on the test set. So, we can only use the training information for normalization. You can refer to this Zhihu answer (https://www.zhihu.com/question/60490799/answer/214685372) for more details. However, this answer (https://www.zhihu.com/question/326050856/answer/1491135429) also said two processes do not have significant differences. Therefore, it remains an open question and can only be answered according to our own problems.
2. The stock prediction dataset is an intern dataset that cannot be released to public. If you are interested in the input/output, you can refer to this repo (https://qlib.readthedocs.io/en/latest/start/getdata.html), which contains a rather small dataset that has exactly the same input/output style with our dataset. However, we did not test our algorithm on this dataset since adarnn was done over 1 year ago when this qlib repo is not released yet. Short answer for your question: the input is just some features defined by professional economist that we do not understand; the output is not actual stock price, but a correlation value that reflects the correlation between predicted value and real market (which I don't understand either since I'm not a finanical guy).

**Comment by wac81** [comment]
> @wac81 Thanks for your interest in this work. Regarding your questions:
> 
> 1. The normalization of train-val-test remains an engineering problem that does not have a definite solution. Actually, someone prefers to normalize first, then split train-test-val; someone prefers to split, then normalize each set with its own statistics. In our work, we adopt the latter: split train-val-test, then normalize each set with only the train statistics. The reason is that test set is actually unseen during training, and the training process cannot have any information on the test set. So, we can only use the training information for normalization. You can refer to this Zhihu answer (https://www.zhihu.com/question/60490799/answer/214685372) for more details. However, this answer (https://www.zhihu.com/question/326050856/answer/1491135429) also said two processes do not have significant differences. Therefore, it remains an open question and can only be answered according to our own problems.
> 2. The stock prediction dataset is an internal dataset that cannot be released to public. If you are interested in the input/output, you can refer to this repo (https://qlib.readthedocs.io/en/latest/start/getdata.html), which contains a rather small dataset that has exactly the same input/output style as our dataset. However, we did not test our algorithm on this dataset since adarnn was done over 1 year ago before the release of qlib. Short answer for your question: the input is just some features defined by professional economist that we do not understand; the output is not actual stock price, but a correlation value that reflects the correlation between predicted value and real market (which I don't understand either since I'm not a finanical guy).

1. Cool! this is exactly the way I expect it to be handled.

2.thank you for the explanation

**Comment by jindongwang** [comment]
I expect next month, depending on whether the first author is busy or not...
