### ISSUE TITLE
adarnn 2021 Temporal distribution characterization

### ISSUE THREAD

**Issue by helloworld1973** [jindongwang/transferlearning#280]
**TDC seems not implement**
When I run the code, I found TDC is not shows up. Is there any reasons that you prefer to not share it or you plan to public it later. 
Besides, For the UCI smartphone activity part, I saw the codes implementation that combine 21 users activities together and test on 9 users. And the experiments more like a cross-users transfer learning compared to the definition of Temporal Covariate Shift.
Thanks a lot.

**Comment by jindongwang** [comment]
Hi, thanks for your interest in this work.
Firstly, for the TDC code, there is a statement here: https://github.com/jindongwang/transferlearning/tree/master/code/deep/adarnn#statement saying that we did not put its code online due to some reasons, but will do it in the future (I really cannot force the previous intern to do it).

Secondly, the UCI activity recognition experiment is designed not to perform cross-person (i.e., train and test on different persons), but to perform cross-time (train and test on different time periods). We notice that as the time goes by, the distribution will also change. Of course, we did this since it is a time series forecasting problem. You can also change it to cross-person experiments (in fact, our very early experiments are for this setting).

**Comment by helloworld1973** [comment]
Many thanks for your explanatation. looking forward more awesome works on it.
