### ISSUE TITLE
Suggestions on improving the integrity of Code Base

### ISSUE THREAD

**Issue by YilinGao-SHU** [jindongwang/transferlearning#382]
Thanks for your contribution to this field. However, some of the existing work is based on the vanilla ResNet-18, and this architecture seems to be lacking in your Code Base. Of course, I also tried to reproduce the results of a simple ResNet-18 based on your framework, but the results are not satisfactory. I wonder if there is any reproduction of this basic Baseline in your future plan? I believe that the reproduction of this Baseline will greatly promote the development of this field.

**Comment by jindongwang** [comment]
Hi @YilinGao-SHU, thank you for your suggestion in adding a ResNet-18 backbone. However, I do not think we should continue using ResNet-18 as backbones given the current status of big models, even ResNet-50 is not useful anymore. I would expect adding ViT series as backbones and this is the future. So, I suggest you move on and embrace ViT. 

If you just want to implement ResNet-18, I do not see any technical obstacles there. You can simply change the backbone in certain model files since ResNet-18 is well implemented in torchvision, just like the way this code uses ResNet-50.

**Comment by YilinGao-SHU** [comment]
Hi, thanks a lot for your answer, but it seems like you misunderstood me. I wondor if you can reproduce a simple Baseline such as vanilla ResNet,, namelly, AGG in Episodic Training for Domain Generalization.

**Comment by jindongwang** [comment]
What's the point in reproducing an obsolete baseline of ResNet-18? I think DomainBed is also obsolete since it focuses only on ResNet-50. I believe soon, most of the DG papers will use ViT instead. So again, forget about ResNet18 and embrace modern backbones:)

**Comment by jindongwang** [comment]
And for that, I believe I'll find some time to build a ViT-based DG codebase to facilitate open research.

**Comment by jindongwang** [comment]
Another thing you should look forward to is CLIP since it beats all the models in DomainBed. I also suggest you design algorithms based on CLIP: https://github.com/jindongwang/transferlearning/tree/master/code/clip

**Comment by YilinGao-SHU** [comment]
Thanks for your suggestion, I will close this issue ~: )
