### ISSUE TITLE
corrupt EXIF data in ImageCLEF-DA dataset?

### ISSUE THREAD

**Issue by LlywelynapGruffudd** [jindongwang/transferlearning#92]
I just download ImageCLEF-DA dataset from your url. when I train P-I, it give me UserWarning:

> UserWarning: Possibly corrupt EXIF data.  Expecting to read 4718592 bytes but only got 0. Skipping tag 0
UserWarning: Possibly corrupt EXIF data.  Expecting to read 395876289 bytes but only got 0. Skipping tag 34464

Is there anything wrong?

**Comment by jindongwang** [comment]
Please indicate from which address you download the dataset

**Comment by LlywelynapGruffudd** [comment]
https://pan.baidu.com/s/1lx2u1SMlSamsHnAPWrAHWA

**Comment by jindongwang** [comment]
This link works for me. I think may there's something wrong with your downloading. Please try re-downloading it.

**Comment by jindongwang** [comment]
@LlywelynapGruffudd Is your problem solved?

**Comment by LlywelynapGruffudd** [comment]
No, and UserWarning appeared when I load the ImageNet ILSVRC 2012 dataset(I), the P dataset is OK.

**Comment by jindongwang** [comment]
Hello, I rerun the code again, it is true that these two images can't be opened. It is possible that I made a mistake while uploading the dataset. Therefore, I re-download the dataset from the dataset provider (who is also the imageclef challenge organizer) and test again, the same error happens. To sum up, it turns out that the organizer has made some mistake while downloading the image from the website.

FYI, the original imageclef challenge is here: https://www.imageclef.org/2014
The dataset organizer provided the dataset here: https://github.com/thuml/CDAN

You can have a try yourself to verify that.

Finally, there are only two images wrong, it does not interrupt the code, which also keeps running. I think it will not influence the final result too much.

**Comment by LlywelynapGruffudd** [comment]
Thank you!
